# Generated by Django 3.0.6 on 2020-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='cat_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
