# Generated by Django 3.0.6 on 2020-06-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0003_addcategory_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcategory',
            name='cat_img',
        ),
    ]
