# Generated by Django 3.0.6 on 2020-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0005_addcategory_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='cat_img',
            field=models.ImageField(default='', upload_to='../product/'),
        ),
    ]
