# Generated by Django 3.0.6 on 2020-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0006_auto_20200621_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcategory',
            name='cat_img',
            field=models.ImageField(default='', upload_to='media/product/'),
        ),
    ]
