# Generated by Django 3.0.6 on 2020-06-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0008_auto_20200621_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=30, null=True)),
                ('suc_cat_img', models.ImageField(default='', upload_to='sub_category/')),
                ('sub_cat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddCategory')),
            ],
        ),
    ]
