# Generated by Django 3.0.6 on 2020-06-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0009_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_cat_type',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_cat_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddCategory'),
        ),
    ]
