# Generated by Django 3.0.6 on 2020-06-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0011_auto_20200625_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='suc_cat_img',
            new_name='sub_cat_img',
        ),
    ]
