# Generated by Django 3.0.6 on 2020-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0013_auto_20200626_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_cat_img',
            field=models.ImageField(default='', upload_to='sub_category/'),
        ),
    ]
