# Generated by Django 3.0.6 on 2020-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0014_auto_20200626_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, null=True)),
                ('brand_img', models.ImageField(default='', upload_to='brand/')),
            ],
        ),
    ]
