# Generated by Django 3.0.6 on 2020-06-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0015_addbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddBrand'),
        ),
    ]
