# Generated by Django 3.0.6 on 2020-06-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0016_subcategory_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_cat_type',
        ),
    ]
