# Generated by Django 3.0.6 on 2020-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0018_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(null=True),
        ),
    ]
