# Generated by Django 3.0.6 on 2020-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0019_auto_20200705_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(null=True),
        ),
    ]
