# Generated by Django 3.0.6 on 2020-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0020_auto_20200705_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_Qty',
            field=models.IntegerField(null=True),
        ),
    ]
