# Generated by Django 3.0.6 on 2020-07-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0022_auto_20200730_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddBrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_sub_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.SubCategory'),
        ),
    ]
