# Generated by Django 3.0.6 on 2020-08-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0025_auto_20200730_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_img',
        ),
    ]
