# Generated by Django 3.0.6 on 2020-08-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0026_remove_product_pro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_sub_category',
        ),
    ]
