# Generated by Django 3.0.6 on 2020-08-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0027_auto_20200802_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_size',
        ),
    ]
