# Generated by Django 3.0.6 on 2020-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0028_remove_product_pro_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_Qty',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
