# Generated by Django 3.0.6 on 2020-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0029_auto_20200802_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(null=True),
        ),
    ]
