# Generated by Django 3.0.6 on 2020-08-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0030_auto_20200802_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_Qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_price',
        ),
        migrations.AddField(
            model_name='product',
            name='pro_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.AddCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adadmin.SubCategory'),
        ),
    ]
