# Generated by Django 3.0.6 on 2020-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0032_product_pro_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(null=True),
        ),
    ]
