# Generated by Django 3.0.6 on 2020-08-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0033_product_pro_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
