# Generated by Django 3.0.6 on 2020-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0034_product_pro_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_Qty',
            field=models.IntegerField(null=True),
        ),
    ]
