# Generated by Django 3.0.6 on 2020-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0035_product_pro_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
