# Generated by Django 3.0.6 on 2020-08-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0036_product_pro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
