# Generated by Django 3.0.6 on 2020-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adadmin', '0037_auto_20200803_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(default='', upload_to='products/'),
        ),
    ]
